# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "helm" # See documentation for possible values
    directory: "/helm/03_grafana" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "helm" # See documentation for possible values
    directory: "/helm/04_postgresql" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "helm" # See documentation for possible values
    directory: "/helm/02_rabbitmq" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "helm" # See documentation for possible values
    directory: "/helm/01_traefik" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "helm" # See documentation for possible values
    directory: "/helm/06_vault" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "helm" # See documentation for possible values
    directory: "/helm/07_prometheus" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "helm" # See documentation for possible values
    directory: "/helm/10_datadog" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "helm" # See documentation for possible values
    directory: "/helm/14_keycloak" # Location of package manifests
    schedule:
      interval: "daily"
