apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-worker-deployment
  labels:
    app: room-worker
spec:
  selector:
    matchLabels:
      app: room-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: room-worker
    spec:
      containers:
      - name: room-worker
        image: ***REMOVED***:9002/roomworker:latest
        ports:
        - containerPort: 8082
      imagePullSecrets:
        - name: nexus
---
apiVersion: v1
kind: Service
metadata:
  name: room-worker
spec:
  selector:
    app: room-worker
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082  
  type: NodePort

