# Test 

environment: prod
roomobserver: 
  port: 30081
  containerPort: 8081
  image: localhost/roomobserver_mq:76
roomstatus: 
  port: 30083
  containerPort: 8081
  image: localhost/roomobstatus:76
roomworker: 
  port: 30082
  containerPort: 8081
  image: localhost/home/roomworker:76
