apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-build-volume
  labels:
    type: nfs
  namespace: dev
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: local-build
    path: "/data/nfs/logs"
  mountOptions:
    - nfsvers=4.2