apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-api-key
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: datadog-api-key
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: datadog
        property: api_key

