apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-frontend-deployment
  labels:
    app: temperature-frontend
  namespace: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: temperature-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: temperature-frontend
    spec:
      containers:
      - name: temperature-frontend
        image: "{{ .Values.temperaturefrontend.image }}:{{ .Values.temperaturefrontend.version }}"
        ports:
        - containerPort: 8081
      imagePullSecrets:
        - name: nexus