FROM python:3.13.6
RUN /usr/local/bin/pip install robotframework
RUN /usr/local/bin/pip install opencv-python
RUN /usr/local/bin/pip install --upgrade robotframework-screencaplibrary
RUN /usr/local/bin/pip install --upgrade robotframework-seleniumlibrary
RUN /usr/local/bin/pip install webdriver-manager
# RUN git clone 