apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-build-volume-vault
  labels:
    type: nfs
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: local-build
    path: "/data/nfs/vault"
  mountOptions:
    - nfsvers=4.2
