#apiVersion: v1
#kind: Namespace
#metadata:
#  name: vault
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-build-volume-vault
#  namespace: vault
spec:
  storageClassName: local-build-volume-vault
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
