apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-driver-storage-class
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ .Values.parameters.hostname }}
  share: {{ .Values.parameters.share }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.2

