apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-observer-deployment
  labels:
    app: room-observer
  namespace: dev
spec:
  selector:
    matchLabels:
      app: room-observer
  replicas: 1
  template:
    metadata:
      labels:
        app: room-observer
    spec:
      containers:
      - name: room-observer
        image: ***REMOVED***:9002/roomobserver:latest
        ports:
        - containerPort: 8081
      imagePullSecrets:
        - name: nexus
---
apiVersion: v1
kind: Service
metadata:
  name: room-observer
  namespace: dev
spec:
  selector:
    app: room-observer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort

