keycloak:
#  global:
#    storageClass: "nfs-csi"
#
  auth:
    adminUser: admin
    adminPassword: password
# 
  postgresql:
    enabled: false
#  
  externalDatabase:
    host: "127.0.0.1"
    port: 12345
    user: postgres
    database: keycloak
    password: 12345

  service:
    type: NodePort
    nodePorts:
      http: "32080"
      https: "32443"
  
  proxy: none

  nodeSelector:
    kubernetes.io/arch: amd64
  
  configuration: |
    # Database
    
    # The database vendor.
    db = postgres
    
    # The username of the database user.
    db-username = user
    
    # The password of the database user.
    db-password = password
    
    # The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
    db-url = jdbc:postgresql://url
    
    # Observability
    
    # If the server should expose healthcheck endpoints.
    health-enabled = true
    
    # If the server should expose metrics endpoints.
    metrics-enabled = true
    
    # HTTP
        
    # The proxy address forwarding mode if the server is behind a reverse proxy.
    proxy = passthrough
    
    # Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
    #spi-sticky-session-encoder-infinispan-should-attach-route=false
    
    # Hostname for the Keycloak server.
    hostname=192.168.2.20
    http-enabled = true
    http-relative-path = /
    http-port = 8080
    https-port = 8443
    hostname-strict = false
    cache-stack = kubernetes
    cache = ispn
    log-level = INFO
    log-console-output = default