apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-observer-deployment
  labels:
    app: room-observer
  namespace: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: room-observer
  replicas: 1
  template:
    metadata:
      labels:
        app: room-observer
    spec:
      hostAliases:
      - ip: {{ .Values.hostAliasDB.ip }}
        hostnames:
        - {{ .Values.hostAliasDB.hostname }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.roomobserver.config }}
      containers:
      - name: room-observer
        image: "{{ .Values.roomobserver.image }}:{{ .Values.roomobserver.version }}"
        resources: {}
#        livenessProbe:
#          httpGet:
#            path: /actuator/health/liveness
#            port: 8081
#          initialDelaySeconds: 240
#        readinessProbe:
#          httpGet:
#            path: /actuator/health/readiness
#            port: 8081
#          initialDelaySeconds: 240
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        ports:
        - containerPort: 8081
        volumeMounts:
            - name: config-volume
              items:
              - key: application.properties 
                path: application.properties
      imagePullSecrets:
        - name: nexus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-status-deployment
  labels:
    app: room-status
  namespace: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: room-status
  replicas: 1
  template:
    metadata:
      labels:
        app: room-status
    spec:
      hostAliases:
      - ip: {{ .Values.hostAliasDB.ip }}
        hostnames:
        - {{ .Values.hostAliasDB.hostname }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.roomstatus.config }}
      containers:
      - name: room-status
        image: "{{ .Values.roomstatus.image }}:{{ .Values.roomstatus.version }}"
        resources: {}
#        livenessProbe:
#          httpGet:
#            path: /actuator/health/liveness
#            port: 8081
#          initialDelaySeconds: 240
#        readinessProbe:
#          httpGet:
#            path: /actuator/health/readiness
#            port: 8081
#          initialDelaySeconds: 240
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]

        ports:
        - containerPort: 8081
        volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      imagePullSecrets:
        - name: nexus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-worker-deployment
  labels:
    app: room-worker
  namespace: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: room-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: room-worker
    spec:
      hostAliases:
      - ip: {{ .Values.hostAliasDB.ip }}
        hostnames:
        - {{ .Values.hostAliasDB.hostname }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.roomworker.config }}
      containers:
      - name: room-worker
        image: "{{ .Values.roomworker.image }}:{{ .Values.roomworker.version }}"
        resources: {}
#        livenessProbe:
#          httpGet:
#            path: /actuator/health/liveness
#            port: 8081
#          initialDelaySeconds: 120
#        readinessProbe:
#          httpGet:
#            path: /actuator/health/readiness
#            port: 8081
#          initialDelaySeconds: 120
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]

        ports:
        - containerPort: 8081
        volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      imagePullSecrets:
        - name: nexus
