apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-observer-deployment
  labels:
    app: room-observer
  namespace: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: room-observer
  replicas: 3
  template:
    metadata:
      labels:
        app: room-observer
    spec:
      hostAliases:
      - ip: {{ .Values.hostAliasDB.ip }}
        hostnames:
        - {{ .Values.hostAliasDB.hostname }}
      nodeSelector:
        kubernetes.io/arch: arm64
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.roomobserver.config }}
        - name: local-build-volume-roomobserver
          persistentVolumeClaim:
            claimName: local-build-volume-roomobserver
      containers:
      - name: room-observer
        image: "{{ .Values.roomobserver.image }}:{{ .Values.roomobserver.version }}"
        #command: [ "/bin/sh", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        livenessProbe:
          httpGet:
            path: /actuator/prometheus
            port: 8081
          initialDelaySeconds: 180
        resources: {}
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        ports:
        - containerPort: 8081
        volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
            - name: local-build-volume-roomobserver
              mountPath: /tmp/log
              subPath: roomobserver
      imagePullSecrets:
        - name: nexus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-status-deployment
  labels:
    app: room-status
  namespace: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: room-status
  replicas: 1
  template:
    metadata:
      labels:
        app: room-status
    spec:
      hostAliases:
      - ip: {{ .Values.hostAliasDB.ip }}
        hostnames:
        - {{ .Values.hostAliasDB.hostname }}
      nodeSelector:
        kubernetes.io/arch: arm64
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.roomstatus.config }}
      containers:
      - name: room-status
        image: "{{ .Values.roomstatus.image }}:{{ .Values.roomstatus.version }}"
        resources: {}
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        ports:
        - containerPort: 8081
        volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      imagePullSecrets:
        - name: nexus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-worker-deployment
  labels:
    app: room-worker
  namespace: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: room-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: room-worker
    spec:
      hostAliases:
      - ip: {{ .Values.hostAliasDB.ip }}
        hostnames:
        - {{ .Values.hostAliasDB.hostname }}
      nodeSelector:
        kubernetes.io/arch: arm64
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.roomworker.config }}
      containers:
      - name: room-worker
        image: "{{ .Values.roomworker.image }}:{{ .Values.roomworker.version }}"
        resources: {}
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]

        ports:
        - containerPort: 8081
        volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      imagePullSecrets:
        - name: nexus
