apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-observer-deployment
  labels:
    app: room-observer
  namespace: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: room-observer
  replicas: 1
  template:
    metadata:
      labels:
        app: room-observer
    spec:
      containers:
      - name: room-observer
        image: {{ .Values.roomobserver.image }}
        ports:
        - containerPort: 8081
      imagePullSecrets:
        - name: nexus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-status-deployment
  labels:
    app: room-status
  namespace: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: room-status
  replicas: 1
  template:
    metadata:
      labels:
        app: room-status
    spec:
      containers:
      - name: room-status
        image: {{ .Values.roomstatus.image }}
        ports:
        - containerPort: 8081
      imagePullSecrets:
        - name: nexus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-worker-deployment
  labels:
    app: room-worker
  namespace: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: room-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: room-worker
    spec:
      containers:
      - name: room-worker
        image: {{ .Values.roomworker.image }}
        ports:
        - containerPort: 8081
      imagePullSecrets:
        - name: nexus
